# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker-service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'worker-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14worker-service.proto\x12\x06worker\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x0bTaskRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"\x1b\n\tTaskReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"2\n\x0cHealthStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\r\"\x1a\n\x0bHealthReply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\x1b\n\x03\x41\x63k\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"M\n\rreplicaStatus\x12\r\n\x05state\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\r\x12\x0b\n\x03pid\x18\x03 \x01(\r\x12\x0c\n\x04port\x18\x04 \x01(\t\"\x14\n\x05Reply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32\xe8\x01\n\rWorkerService\x12\x32\n\x08PushTask\x12\x13.worker.TaskRequest\x1a\x11.worker.TaskReply\x12=\n\x10sendHealthupdate\x12\x14.worker.HealthStatus\x1a\x13.worker.HealthReply\x12\x37\n\x0fRegisterReplica\x12\x15.worker.replicaStatus\x1a\r.worker.Reply\x12+\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x0b.worker.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=61
  _globals['_TASKREQUEST']._serialized_end=104
  _globals['_TASKREPLY']._serialized_start=106
  _globals['_TASKREPLY']._serialized_end=133
  _globals['_HEALTHSTATUS']._serialized_start=135
  _globals['_HEALTHSTATUS']._serialized_end=185
  _globals['_HEALTHREPLY']._serialized_start=187
  _globals['_HEALTHREPLY']._serialized_end=213
  _globals['_ACK']._serialized_start=215
  _globals['_ACK']._serialized_end=242
  _globals['_REPLICASTATUS']._serialized_start=244
  _globals['_REPLICASTATUS']._serialized_end=321
  _globals['_REPLY']._serialized_start=323
  _globals['_REPLY']._serialized_end=343
  _globals['_WORKERSERVICE']._serialized_start=346
  _globals['_WORKERSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
