scrape_configs:
  # This job discovers instances on port 8000 but explicitly drops
  # any instance with the Name tag 'head-controller'.
  

  # Job to scrape vLLM replicas on port 9000
  - job_name: 'vllm_replicas_9000'
    ec2_sd_configs:
      - region: us-east-1
        port: 9000
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Service]
        regex: 'ModelScheduler'
        action: keep

  # Job to scrape vLLM replicas on port 9001
  - job_name: 'vllm_replicas_9001'
    ec2_sd_configs:
      - region: us-east-1
        port: 9001
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Service]
        regex: 'ModelScheduler'
        action: keep

  # Job to scrape vLLM replicas on port 9002
  - job_name: 'vllm_replicas_9002'
    ec2_sd_configs:
      - region: us-east-1
        port: 9002
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Service]
        regex: 'ModelScheduler'
        action: keep

  # Job to scrape the user-facing metrics from the head-controller's proxy
  - job_name: 'head_controller_proxy'
    ec2_sd_configs:
      - region: us-east-1
        port: 8000 # FastAPI serves metrics on same port as HTTP
    relabel_configs:
      # Keep only the instance with the name 'head-controller'
      - source_labels: [__meta_ec2_tag_Name]
        regex: 'head-controller'
        action: keep
    
