// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: headnode-service.proto
// Protobuf C++ Version: 5.29.3

#ifndef headnode_2dservice_2eproto_2epb_2eh
#define headnode_2dservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_headnode_2dservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_headnode_2dservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_headnode_2dservice_2eproto;
namespace raylet {
class HeadNodeReply;
struct HeadNodeReplyDefaultTypeInternal;
extern HeadNodeReplyDefaultTypeInternal _HeadNodeReply_default_instance_;
class HeadNodeRequest;
struct HeadNodeRequestDefaultTypeInternal;
extern HeadNodeRequestDefaultTypeInternal _HeadNodeRequest_default_instance_;
}  // namespace raylet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace raylet {

// ===================================================================


// -------------------------------------------------------------------

class HeadNodeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:raylet.HeadNodeRequest) */ {
 public:
  inline HeadNodeRequest() : HeadNodeRequest(nullptr) {}
  ~HeadNodeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HeadNodeRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HeadNodeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HeadNodeRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline HeadNodeRequest(const HeadNodeRequest& from) : HeadNodeRequest(nullptr, from) {}
  inline HeadNodeRequest(HeadNodeRequest&& from) noexcept
      : HeadNodeRequest(nullptr, std::move(from)) {}
  inline HeadNodeRequest& operator=(const HeadNodeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeadNodeRequest& operator=(HeadNodeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeadNodeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeadNodeRequest* internal_default_instance() {
    return reinterpret_cast<const HeadNodeRequest*>(
        &_HeadNodeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HeadNodeRequest& a, HeadNodeRequest& b) { a.Swap(&b); }
  inline void Swap(HeadNodeRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeadNodeRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeadNodeRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HeadNodeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HeadNodeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HeadNodeRequest& from) { HeadNodeRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HeadNodeRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "raylet.HeadNodeRequest"; }

 protected:
  explicit HeadNodeRequest(::google::protobuf::Arena* arena);
  HeadNodeRequest(::google::protobuf::Arena* arena, const HeadNodeRequest& from);
  HeadNodeRequest(::google::protobuf::Arena* arena, HeadNodeRequest&& from) noexcept
      : HeadNodeRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFinalResultFieldNumber = 1,
    kOriginalTaskIdFieldNumber = 2,
  };
  // string final_result = 1;
  void clear_final_result() ;
  const std::string& final_result() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_final_result(Arg_&& arg, Args_... args);
  std::string* mutable_final_result();
  PROTOBUF_NODISCARD std::string* release_final_result();
  void set_allocated_final_result(std::string* value);

  private:
  const std::string& _internal_final_result() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_final_result(
      const std::string& value);
  std::string* _internal_mutable_final_result();

  public:
  // string original_task_id = 2;
  void clear_original_task_id() ;
  const std::string& original_task_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_original_task_id(Arg_&& arg, Args_... args);
  std::string* mutable_original_task_id();
  PROTOBUF_NODISCARD std::string* release_original_task_id();
  void set_allocated_original_task_id(std::string* value);

  private:
  const std::string& _internal_original_task_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_original_task_id(
      const std::string& value);
  std::string* _internal_mutable_original_task_id();

  public:
  // @@protoc_insertion_point(class_scope:raylet.HeadNodeRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      59, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HeadNodeRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr final_result_;
    ::google::protobuf::internal::ArenaStringPtr original_task_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_headnode_2dservice_2eproto;
};
// -------------------------------------------------------------------

class HeadNodeReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:raylet.HeadNodeReply) */ {
 public:
  inline HeadNodeReply() : HeadNodeReply(nullptr) {}
  ~HeadNodeReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HeadNodeReply* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HeadNodeReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HeadNodeReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline HeadNodeReply(const HeadNodeReply& from) : HeadNodeReply(nullptr, from) {}
  inline HeadNodeReply(HeadNodeReply&& from) noexcept
      : HeadNodeReply(nullptr, std::move(from)) {}
  inline HeadNodeReply& operator=(const HeadNodeReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeadNodeReply& operator=(HeadNodeReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeadNodeReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeadNodeReply* internal_default_instance() {
    return reinterpret_cast<const HeadNodeReply*>(
        &_HeadNodeReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(HeadNodeReply& a, HeadNodeReply& b) { a.Swap(&b); }
  inline void Swap(HeadNodeReply* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeadNodeReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeadNodeReply* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HeadNodeReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HeadNodeReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HeadNodeReply& from) { HeadNodeReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HeadNodeReply* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "raylet.HeadNodeReply"; }

 protected:
  explicit HeadNodeReply(::google::protobuf::Arena* arena);
  HeadNodeReply(::google::protobuf::Arena* arena, const HeadNodeReply& from);
  HeadNodeReply(::google::protobuf::Arena* arena, HeadNodeReply&& from) noexcept
      : HeadNodeReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kAckFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // bool ack = 1;
  void clear_ack() ;
  bool ack() const;
  void set_ack(bool value);

  private:
  bool _internal_ack() const;
  void _internal_set_ack(bool value);

  public:
  // @@protoc_insertion_point(class_scope:raylet.HeadNodeReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      36, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HeadNodeReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    bool ack_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_headnode_2dservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HeadNodeRequest

// string final_result = 1;
inline void HeadNodeRequest::clear_final_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.final_result_.ClearToEmpty();
}
inline const std::string& HeadNodeRequest::final_result() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:raylet.HeadNodeRequest.final_result)
  return _internal_final_result();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HeadNodeRequest::set_final_result(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.final_result_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:raylet.HeadNodeRequest.final_result)
}
inline std::string* HeadNodeRequest::mutable_final_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_final_result();
  // @@protoc_insertion_point(field_mutable:raylet.HeadNodeRequest.final_result)
  return _s;
}
inline const std::string& HeadNodeRequest::_internal_final_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.final_result_.Get();
}
inline void HeadNodeRequest::_internal_set_final_result(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.final_result_.Set(value, GetArena());
}
inline std::string* HeadNodeRequest::_internal_mutable_final_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.final_result_.Mutable( GetArena());
}
inline std::string* HeadNodeRequest::release_final_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:raylet.HeadNodeRequest.final_result)
  return _impl_.final_result_.Release();
}
inline void HeadNodeRequest::set_allocated_final_result(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.final_result_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.final_result_.IsDefault()) {
    _impl_.final_result_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:raylet.HeadNodeRequest.final_result)
}

// string original_task_id = 2;
inline void HeadNodeRequest::clear_original_task_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.original_task_id_.ClearToEmpty();
}
inline const std::string& HeadNodeRequest::original_task_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:raylet.HeadNodeRequest.original_task_id)
  return _internal_original_task_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HeadNodeRequest::set_original_task_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.original_task_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:raylet.HeadNodeRequest.original_task_id)
}
inline std::string* HeadNodeRequest::mutable_original_task_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_original_task_id();
  // @@protoc_insertion_point(field_mutable:raylet.HeadNodeRequest.original_task_id)
  return _s;
}
inline const std::string& HeadNodeRequest::_internal_original_task_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.original_task_id_.Get();
}
inline void HeadNodeRequest::_internal_set_original_task_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.original_task_id_.Set(value, GetArena());
}
inline std::string* HeadNodeRequest::_internal_mutable_original_task_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.original_task_id_.Mutable( GetArena());
}
inline std::string* HeadNodeRequest::release_original_task_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:raylet.HeadNodeRequest.original_task_id)
  return _impl_.original_task_id_.Release();
}
inline void HeadNodeRequest::set_allocated_original_task_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.original_task_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.original_task_id_.IsDefault()) {
    _impl_.original_task_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:raylet.HeadNodeRequest.original_task_id)
}

// -------------------------------------------------------------------

// HeadNodeReply

// bool ack = 1;
inline void HeadNodeReply::clear_ack() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ack_ = false;
}
inline bool HeadNodeReply::ack() const {
  // @@protoc_insertion_point(field_get:raylet.HeadNodeReply.ack)
  return _internal_ack();
}
inline void HeadNodeReply::set_ack(bool value) {
  _internal_set_ack(value);
  // @@protoc_insertion_point(field_set:raylet.HeadNodeReply.ack)
}
inline bool HeadNodeReply::_internal_ack() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ack_;
}
inline void HeadNodeReply::_internal_set_ack(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ack_ = value;
}

// string message = 2;
inline void HeadNodeReply::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& HeadNodeReply::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:raylet.HeadNodeReply.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HeadNodeReply::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:raylet.HeadNodeReply.message)
}
inline std::string* HeadNodeReply::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:raylet.HeadNodeReply.message)
  return _s;
}
inline const std::string& HeadNodeReply::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void HeadNodeReply::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* HeadNodeReply::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* HeadNodeReply::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:raylet.HeadNodeReply.message)
  return _impl_.message_.Release();
}
inline void HeadNodeReply::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:raylet.HeadNodeReply.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace raylet


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // headnode_2dservice_2eproto_2epb_2eh
