// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: headnode-service.proto

#include "headnode-service.pb.h"
#include "headnode-service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace raylet {

static const char* HeadNodeService_method_names[] = {
  "/raylet.HeadNodeService/ReportResult",
};

std::unique_ptr< HeadNodeService::Stub> HeadNodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HeadNodeService::Stub> stub(new HeadNodeService::Stub(channel, options));
  return stub;
}

HeadNodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReportResult_(HeadNodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HeadNodeService::Stub::ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::raylet::HeadNodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportResult_, context, request, response);
}

void HeadNodeService::Stub::async::ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportResult_, context, request, response, std::move(f));
}

void HeadNodeService::Stub::async::ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>* HeadNodeService::Stub::PrepareAsyncReportResultRaw(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raylet::HeadNodeReply, ::raylet::HeadNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>* HeadNodeService::Stub::AsyncReportResultRaw(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

HeadNodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HeadNodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HeadNodeService::Service, ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HeadNodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raylet::HeadNodeRequest* req,
             ::raylet::HeadNodeReply* resp) {
               return service->ReportResult(ctx, req, resp);
             }, this)));
}

HeadNodeService::Service::~Service() {
}

::grpc::Status HeadNodeService::Service::ReportResult(::grpc::ServerContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace raylet

