// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: headnode-service.proto
#ifndef GRPC_headnode_2dservice_2eproto__INCLUDED
#define GRPC_headnode_2dservice_2eproto__INCLUDED

#include "headnode-service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace raylet {

class HeadNodeService final {
 public:
  static constexpr char const* service_full_name() {
    return "raylet.HeadNodeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::raylet::HeadNodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raylet::HeadNodeReply>> AsyncReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raylet::HeadNodeReply>>(AsyncReportResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raylet::HeadNodeReply>> PrepareAsyncReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raylet::HeadNodeReply>>(PrepareAsyncReportResultRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raylet::HeadNodeReply>* AsyncReportResultRaw(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raylet::HeadNodeReply>* PrepareAsyncReportResultRaw(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::raylet::HeadNodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>> AsyncReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>>(AsyncReportResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>> PrepareAsyncReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>>(PrepareAsyncReportResultRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response, std::function<void(::grpc::Status)>) override;
      void ReportResult(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>* AsyncReportResultRaw(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raylet::HeadNodeReply>* PrepareAsyncReportResultRaw(::grpc::ClientContext* context, const ::raylet::HeadNodeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReportResult_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ReportResult(::grpc::ServerContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportResult() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReportResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportResult(::grpc::ServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportResult(::grpc::ServerContext* context, ::raylet::HeadNodeRequest* request, ::grpc::ServerAsyncResponseWriter< ::raylet::HeadNodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReportResult<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ReportResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportResult() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raylet::HeadNodeRequest* request, ::raylet::HeadNodeReply* response) { return this->ReportResult(context, request, response); }));}
    void SetMessageAllocatorFor_ReportResult(
        ::grpc::MessageAllocator< ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportResult(::grpc::ServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportResult(
      ::grpc::CallbackServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ReportResult<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReportResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportResult() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReportResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportResult(::grpc::ServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportResult() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReportResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportResult(::grpc::ServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportResult() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportResult(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportResult(::grpc::ServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportResult() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raylet::HeadNodeRequest, ::raylet::HeadNodeReply>* streamer) {
                       return this->StreamedReportResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportResult(::grpc::ServerContext* /*context*/, const ::raylet::HeadNodeRequest* /*request*/, ::raylet::HeadNodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raylet::HeadNodeRequest,::raylet::HeadNodeReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ReportResult<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ReportResult<Service > StreamedService;
};

}  // namespace raylet


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_headnode_2dservice_2eproto__INCLUDED
