// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker-service.proto
// Protobuf C++ Version: 5.29.3

#ifndef worker_2dservice_2eproto_2epb_2eh
#define worker_2dservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_worker_2dservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_worker_2dservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_worker_2dservice_2eproto;
namespace worker {
class WorkerReply;
struct WorkerReplyDefaultTypeInternal;
extern WorkerReplyDefaultTypeInternal _WorkerReply_default_instance_;
class WorkerRequest;
struct WorkerRequestDefaultTypeInternal;
extern WorkerRequestDefaultTypeInternal _WorkerRequest_default_instance_;
}  // namespace worker
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace worker {

// ===================================================================


// -------------------------------------------------------------------

class WorkerRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:worker.WorkerRequest) */ {
 public:
  inline WorkerRequest() : WorkerRequest(nullptr) {}
  ~WorkerRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WorkerRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WorkerRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WorkerRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline WorkerRequest(const WorkerRequest& from) : WorkerRequest(nullptr, from) {}
  inline WorkerRequest(WorkerRequest&& from) noexcept
      : WorkerRequest(nullptr, std::move(from)) {}
  inline WorkerRequest& operator=(const WorkerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkerRequest& operator=(WorkerRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WorkerRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const WorkerRequest* internal_default_instance() {
    return reinterpret_cast<const WorkerRequest*>(
        &_WorkerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WorkerRequest& a, WorkerRequest& b) { a.Swap(&b); }
  inline void Swap(WorkerRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkerRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WorkerRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WorkerRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WorkerRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WorkerRequest& from) { WorkerRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WorkerRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "worker.WorkerRequest"; }

 protected:
  explicit WorkerRequest(::google::protobuf::Arena* arena);
  WorkerRequest(::google::protobuf::Arena* arena, const WorkerRequest& from);
  WorkerRequest(::google::protobuf::Arena* arena, WorkerRequest&& from) noexcept
      : WorkerRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataToProcessFieldNumber = 1,
  };
  // string data_to_process = 1;
  void clear_data_to_process() ;
  const std::string& data_to_process() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data_to_process(Arg_&& arg, Args_... args);
  std::string* mutable_data_to_process();
  PROTOBUF_NODISCARD std::string* release_data_to_process();
  void set_allocated_data_to_process(std::string* value);

  private:
  const std::string& _internal_data_to_process() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data_to_process(
      const std::string& value);
  std::string* _internal_mutable_data_to_process();

  public:
  // @@protoc_insertion_point(class_scope:worker.WorkerRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const WorkerRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr data_to_process_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_worker_2dservice_2eproto;
};
// -------------------------------------------------------------------

class WorkerReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:worker.WorkerReply) */ {
 public:
  inline WorkerReply() : WorkerReply(nullptr) {}
  ~WorkerReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WorkerReply* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WorkerReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WorkerReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline WorkerReply(const WorkerReply& from) : WorkerReply(nullptr, from) {}
  inline WorkerReply(WorkerReply&& from) noexcept
      : WorkerReply(nullptr, std::move(from)) {}
  inline WorkerReply& operator=(const WorkerReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkerReply& operator=(WorkerReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WorkerReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const WorkerReply* internal_default_instance() {
    return reinterpret_cast<const WorkerReply*>(
        &_WorkerReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(WorkerReply& a, WorkerReply& b) { a.Swap(&b); }
  inline void Swap(WorkerReply* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkerReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WorkerReply* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WorkerReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WorkerReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WorkerReply& from) { WorkerReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WorkerReply* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "worker.WorkerReply"; }

 protected:
  explicit WorkerReply(::google::protobuf::Arena* arena);
  WorkerReply(::google::protobuf::Arena* arena, const WorkerReply& from);
  WorkerReply(::google::protobuf::Arena* arena, WorkerReply&& from) noexcept
      : WorkerReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kProcessedDataFieldNumber = 1,
    kSuccessFieldNumber = 2,
  };
  // string processed_data = 1;
  void clear_processed_data() ;
  const std::string& processed_data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_processed_data(Arg_&& arg, Args_... args);
  std::string* mutable_processed_data();
  PROTOBUF_NODISCARD std::string* release_processed_data();
  void set_allocated_processed_data(std::string* value);

  private:
  const std::string& _internal_processed_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_processed_data(
      const std::string& value);
  std::string* _internal_mutable_processed_data();

  public:
  // bool success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:worker.WorkerReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const WorkerReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr processed_data_;
    bool success_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_worker_2dservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WorkerRequest

// string data_to_process = 1;
inline void WorkerRequest::clear_data_to_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_to_process_.ClearToEmpty();
}
inline const std::string& WorkerRequest::data_to_process() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:worker.WorkerRequest.data_to_process)
  return _internal_data_to_process();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void WorkerRequest::set_data_to_process(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_to_process_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:worker.WorkerRequest.data_to_process)
}
inline std::string* WorkerRequest::mutable_data_to_process() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data_to_process();
  // @@protoc_insertion_point(field_mutable:worker.WorkerRequest.data_to_process)
  return _s;
}
inline const std::string& WorkerRequest::_internal_data_to_process() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_to_process_.Get();
}
inline void WorkerRequest::_internal_set_data_to_process(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_to_process_.Set(value, GetArena());
}
inline std::string* WorkerRequest::_internal_mutable_data_to_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_to_process_.Mutable( GetArena());
}
inline std::string* WorkerRequest::release_data_to_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:worker.WorkerRequest.data_to_process)
  return _impl_.data_to_process_.Release();
}
inline void WorkerRequest::set_allocated_data_to_process(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_to_process_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_to_process_.IsDefault()) {
    _impl_.data_to_process_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:worker.WorkerRequest.data_to_process)
}

// -------------------------------------------------------------------

// WorkerReply

// string processed_data = 1;
inline void WorkerReply::clear_processed_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processed_data_.ClearToEmpty();
}
inline const std::string& WorkerReply::processed_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:worker.WorkerReply.processed_data)
  return _internal_processed_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void WorkerReply::set_processed_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processed_data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:worker.WorkerReply.processed_data)
}
inline std::string* WorkerReply::mutable_processed_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_processed_data();
  // @@protoc_insertion_point(field_mutable:worker.WorkerReply.processed_data)
  return _s;
}
inline const std::string& WorkerReply::_internal_processed_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.processed_data_.Get();
}
inline void WorkerReply::_internal_set_processed_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processed_data_.Set(value, GetArena());
}
inline std::string* WorkerReply::_internal_mutable_processed_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.processed_data_.Mutable( GetArena());
}
inline std::string* WorkerReply::release_processed_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:worker.WorkerReply.processed_data)
  return _impl_.processed_data_.Release();
}
inline void WorkerReply::set_allocated_processed_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processed_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.processed_data_.IsDefault()) {
    _impl_.processed_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:worker.WorkerReply.processed_data)
}

// bool success = 2;
inline void WorkerReply::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool WorkerReply::success() const {
  // @@protoc_insertion_point(field_get:worker.WorkerReply.success)
  return _internal_success();
}
inline void WorkerReply::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:worker.WorkerReply.success)
}
inline bool WorkerReply::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void WorkerReply::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace worker


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // worker_2dservice_2eproto_2epb_2eh
