// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker-service.proto

#include "worker-service.pb.h"
#include "worker-service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace worker {

static const char* WorkerService_method_names[] = {
  "/worker.WorkerService/ProcessData",
};

std::unique_ptr< WorkerService::Stub> WorkerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerService::Stub> stub(new WorkerService::Stub(channel, options));
  return stub;
}

WorkerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessData_(WorkerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerService::Stub::ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::worker::WorkerReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::worker::WorkerRequest, ::worker::WorkerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessData_, context, request, response);
}

void WorkerService::Stub::async::ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::worker::WorkerRequest, ::worker::WorkerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessData_, context, request, response, std::move(f));
}

void WorkerService::Stub::async::ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>* WorkerService::Stub::PrepareAsyncProcessDataRaw(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::worker::WorkerReply, ::worker::WorkerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>* WorkerService::Stub::AsyncProcessDataRaw(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerService::Service, ::worker::WorkerRequest, ::worker::WorkerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::worker::WorkerRequest* req,
             ::worker::WorkerReply* resp) {
               return service->ProcessData(ctx, req, resp);
             }, this)));
}

WorkerService::Service::~Service() {
}

::grpc::Status WorkerService::Service::ProcessData(::grpc::ServerContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace worker

