// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker-service.proto
#ifndef GRPC_worker_2dservice_2eproto__INCLUDED
#define GRPC_worker_2dservice_2eproto__INCLUDED

#include "worker-service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace worker {

class WorkerService final {
 public:
  static constexpr char const* service_full_name() {
    return "worker.WorkerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::worker::WorkerReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::worker::WorkerReply>> AsyncProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::worker::WorkerReply>>(AsyncProcessDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::worker::WorkerReply>> PrepareAsyncProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::worker::WorkerReply>>(PrepareAsyncProcessDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::worker::WorkerReply>* AsyncProcessDataRaw(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::worker::WorkerReply>* PrepareAsyncProcessDataRaw(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::worker::WorkerReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>> AsyncProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>>(AsyncProcessDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>> PrepareAsyncProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>>(PrepareAsyncProcessDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response, std::function<void(::grpc::Status)>) override;
      void ProcessData(::grpc::ClientContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>* AsyncProcessDataRaw(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::worker::WorkerReply>* PrepareAsyncProcessDataRaw(::grpc::ClientContext* context, const ::worker::WorkerRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ProcessData(::grpc::ServerContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessData(::grpc::ServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessData(::grpc::ServerContext* context, ::worker::WorkerRequest* request, ::grpc::ServerAsyncResponseWriter< ::worker::WorkerReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::worker::WorkerRequest, ::worker::WorkerReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::worker::WorkerRequest* request, ::worker::WorkerReply* response) { return this->ProcessData(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessData(
        ::grpc::MessageAllocator< ::worker::WorkerRequest, ::worker::WorkerReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::worker::WorkerRequest, ::worker::WorkerReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessData(::grpc::ServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessData(
      ::grpc::CallbackServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessData(::grpc::ServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessData(::grpc::ServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessData(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessData(::grpc::ServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::worker::WorkerRequest, ::worker::WorkerReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::worker::WorkerRequest, ::worker::WorkerReply>* streamer) {
                       return this->StreamedProcessData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessData(::grpc::ServerContext* /*context*/, const ::worker::WorkerRequest* /*request*/, ::worker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::worker::WorkerRequest,::worker::WorkerReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessData<Service > StreamedService;
};

}  // namespace worker


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_worker_2dservice_2eproto__INCLUDED
